-- Drop tables if they exist (for testing purposes)
DROP TABLE IF EXISTS CLASSE;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS STUDENT;

-- Create tables
CREATE TABLE CLASSE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(50)
);

CREATE TABLE SUBJECT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(50)
);

CREATE TABLE TEACHER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    MATRICULE VARCHAR(50) NOT NULL
);

CREATE TABLE STUDENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    MATRICULE VARCHAR(50) NOT NULL
);
